projects:
  - name: kubernetes
    repo: https://github.com/kubernetes/kubernetes.git
    version: v1.21.2
    env:
      - name: VERSION_PRERELEASE
        value: "undistro"
      - name: KUBE_DOCKER_REGISTRY
        value: "docker.io/getupioundistro"
      - name: KUBE_RELEASE_RUN_TESTS
        value: "n"
    releaseCommand:
      name: make
      args: ["release"]
  - name: coredns
    repo: https://github.com/coredns/coredns.git
    version: v1.8.4
    releaseCommand:
      name: make
      args:
        [
          "DOCKER=docker.io/getupioundistro",
          "-f",
          "Makefile.release",
          "release",
        ]
    packageImagesCommand:
      name: make
      args:
        [
          "DOCKER=docker.io/getupioundistro",
          "-f",
          "Makefile.release",
          "docker-build",
          "docker-push",
        ]
  - name: etcd
    repo: https://github.com/etcd-io/etcd.git
    version: v3.5.0
    env:
      - name: TAG
        value: "docker.io/getupioundistro"
      - name: VERSION
        value: v3.5.0
    releaseCommand:
      name: bash
      args: [
          "-c",
          'for TARGET_ARCH in "amd64" "arm64" "ppc64le" "s390x" ""; do
          GOOS=linux GOARCH=${TARGET_ARCH} ./scripts/build-docker v3.5.0
          done',
        ]
    packageImagesCommand:
      name: bash
      args: [
          "-c",
          'for TARGET_ARCH in "amd64" "-arm64" "-ppc64le" "-s390x" ""; do
          docker push docker.io/getupioundistro/etcd:v3.5.0${TARGET_ARCH}
          done',
        ]
