projects:
  - name: kubernetes
    repo: https://github.com/kubernetes/kubernetes.git
    version: v1.20.8
    env:
      - name: VERSION_PRERELEASE
        value: "undistro"
      - name: KUBE_DOCKER_REGISTRY
        value: "docker.io/getupioundistro"
      - name: KUBE_RELEASE_RUN_TESTS
        value: "n"
    releaseCommand:
      name: make
      args: ["release"]
  - name: coredns
    repo: https://github.com/coredns/coredns.git
    version: v1.8.4
    env:
      - name: DOCKER
        value: "docker.io/getupioundistro"
    releaseCommand:
      name: make
      args: ["-f", "Makefile.release", "release"]
    packageImagesCommand:
      name: make
      args: ["-f", "Makefile.release", "docker-build", "docker-push"]
