projects:
  - name: kubernetes
    repo: https://github.com/kubernetes/kubernetes.git
    version: v1.18.20
    env:
      - name: VERSION_PRERELEASE
        value: "undistro"
      - name: KUBE_DOCKER_REGISTRY
        value: "docker.io/getupioundistro"
      - name: KUBE_RELEASE_RUN_TESTS
        value: "n"
    releaseCommand:
      name: make
      args: ["release"]
  - name: coredns
    repo: https://github.com/coredns/coredns.git
    version: v1.8.4
    releaseCommand:
      name: make
      args:
        [
          "DOCKER=docker.io/getupioundistro",
          "-f",
          "Makefile.release",
          "release",
        ]
    packageImagesCommand:
      name: make
      args:
        [
          "DOCKER=docker.io/getupioundistro",
          "-f",
          "Makefile.release",
          "docker-build",
          "docker-push",
        ]
