name: Kubernetes

on:
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run kubernetes Build
        run: ./k8s.sh v1.21.1
