name: Kubernetes

on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run kubernetes Build
        env:
          DOCKER_BUILDKIT: "1"
        run: go run main.go
