name: Kubernetes Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.undistro.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Version vars
        run: ./hack/version.sh

      - name: Run kubernetes Build
        env:
          DOCKER_BUILDKIT: "1"
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          go run main.go -versions=$(echo "${GIT_MAJOR}.${GIT_MINOR}")
          ./hack/clean-volumes.sh
